apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
  namespace: backend
  labels:
    component: backend
spec:
  hard:
    # Compute Resources
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    
    # Storage
    requests.storage: "50Gi"
    persistentvolumeclaims: "10"
    
    # Object Counts
    pods: "20"
    replicationcontrollers: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"
    
    # Extended Resources
    count/deployments.apps: "10"
    count/replicasets.apps: "20"
    count/statefulsets.apps: "5"
    count/jobs.batch: "10"
    count/cronjobs.batch: "5"