apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend

resources:
- deployment.yaml
- service.yaml

labels:
- pairs:
    app: image-service
    component: backend
    version: v1