apiVersion: v1
kind: Service
metadata:
  name: image-service
  namespace: backend
  labels:
    app: image-service
    component: backend
    managed-by: gitops
spec:
  selector:
    app: image-service
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP