apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: backend
  labels:
    app: api-service
    component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: api-service