# Kube-Prometheus-Stack Configuration for SRE Task
# This file contains the Helm values for monitoring deployment

prometheus:
  prometheusSpec:
    retention: 7d
    retentionSize: "10GiB"
    
    # Storage configuration
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

    # Resource configuration
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

    # Service discovery for our applications
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

# Grafana configuration
grafana:
  enabled: true
  
  # Persistence
  persistence:
    enabled: true
    storageClassName: gp2
    size: 5Gi

  # Resources
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # Basic configuration
  grafana.ini:
    server:
      root_url: "http://localhost:3000"
    security:
      admin_user: admin
    users:
      allow_sign_up: false
    auth.anonymous:
      enabled: false

# AlertManager configuration
alertmanager:
  enabled: true
  alertmanagerSpec:
    # Storage
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

    # Resources
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

# Component configurations
nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

# Disable some components for POC
coreDns:
  enabled: false

kubeProxy:
  enabled: false

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false