apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- servicemonitor.yaml
- prometheusrule.yaml

labels:
- pairs:
    app: monitoring
    component: monitoring
    version: v1
    managed-by: gitops

namespace: monitoring