apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: backend
  labels:
    app: auth-service
    component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: auth-service