apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-service-account
  namespace: frontend
  labels:
    app: frontend-service
    component: frontend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: frontend
  name: frontend-role
  labels:
    app: frontend-service
    component: frontend
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-role-binding
  namespace: frontend
  labels:
    app: frontend-service
    component: frontend
subjects:
- kind: ServiceAccount
  name: frontend-service-account
  namespace: frontend
roleRef:
  kind: Role
  name: frontend-role
  apiGroup: rbac.authorization.k8s.io