apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-service-account.yaml
  - frontend-service-account.yaml

commonLabels:
  managed-by: kustomize
  environment: poc